# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en  
  title: Sergey Davydov
  params:
    description: Blog
  menu:
    main:
      - name: Bio
        url: '/en/'
        weight: 1
      - name: Papers
        url: '/publication/'
        weight: 2
      - name: News
        url: '/post/'
        weight: 3
      - name: Experience
        url: '/experience/'
        weight: 4      

ru:
  languageCode: ru
  contentDir: content/ru  
  title: Сергей Давыдов
  params:
    description: Блог
  menu:
    main:
      - name: Главная
        url: '/ru/'
        weight: 1
      - name: Бумаги
        url: '/publication/'
        weight: 2
      - name: Новости
        url: '/post/'
        weight: 3
      - name: Опыт
        url: '/experience/'
        weight: 4
